title: <p align="center"> Gaurav Malhotra </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://in.linkedin.com/in/gaurav-malhotra-2606">LinkedIn</a> |
  <a href="https://github.com/MrRobo-t">GitHub</a>
  
  <br>   
  I'm working on product development, enhancemnets and improvements.
  Worked with Amagi Corporation at Product Development team.
  Working across multilpe domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
